---
title: "Create reference grid Gran Canaria"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output: 
  
  html_document:
      code_folding: hide
      toc: true
      toc_float: true
      toc_collapsed: true
  editor_options:
      chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(here)
opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
opts_knit$set(root.dir = here::here())

library(tidyverse)     # Easy data prep, cleaning and visualization
library(sf)            # Work with simple features
```

# Data preparation

We first read in the map of Gran Canaria and set project crs to UTM zone 28R.

```{r}
# Location of data en output folders
data_path <- here("data", "raw")
out_path <- here("data", "processed")

# Reference coordinate system: UTM zone 28R
proj_utm_zone <- "28R"
proj_crs <- 32628

# Read layers
gran_canaria <- st_read(paste(data_path, "GranCanaria.shp", sep = "/"))

# Set project crs
gran_canaria <- st_transform(gran_canaria, crs = proj_crs)
```

The map looks as follows:

```{r}
# Create theme for plotting map
mytheme <- theme(panel.grid.major = element_line(color = "grey", 
                                                 linetype = "dashed", 
                                                 size = 0.3),
                 panel.background = element_rect(fill = "aliceblue"),
                 axis.title = element_blank())

base_plot <- gran_canaria %>%
  ggplot() +
    geom_sf(fill = "khaki3") +
    mytheme
base_plot
```
